### PR TITLE
Feature/login

### LINKED ISSUE #16: Login Page With Signup
NOTE: users can switch between the registration form ui by clicking ‘already have an account? login’ and ‘not registered yet? sign up’ links. (animation)

### PR DESCRIPTION
**Pull request by Blargian**
Hello, I am opening a pull request for preliminary review (I expect there will be lots of changes that will need to be made still) 😄  

I have made additions:

- Login page (localhost:3000/login)
- LoginSignup component (consisting of LoginInfo and LoginForm components) / switches between the two components
- Styling for mobile and desktop versions 

Still to do:
- Add animation on transition from login to signup 

desktop-login

desktop-mobile

I appreciate any feedback from the team and I will fix any issues so please don't hesitate to tell me about any problems with this PR.

### CODE REVIEW

**Review by chamodshehanka — CHANGES_REQUESTED** [review]
Thanks for sending this PR, I really appreciate that. 

Can you move Login stuff to `components/Login` and `components/SignUp`?

Then we're good to go 🔥🥳

**Review by chamodshehanka — CHANGES_REQUESTED** [review]
CI is failing too, Please remove unused vars @Blargian.

@sithumonline, Seems like you haven't configured `eslint` and `husky` properly!!!!!!!!

Screenshot 2021-06-30 at 20 59 24

**Review by sithumonline — DISMISSED** [review]
Good Job

**Comment by sithumonline** [comment]
> CI is failing too, Please remove unused vars @Blargian.
> 
> @sithumonline, Seems like you haven't configured `eslint` and `husky` properly!!!!!!!!
> 
> Screenshot 2021-06-30 at 20 59 24
> 

Yha... Maybe can you fix it @Shehanka

**Review by sithumonline — CHANGES_REQUESTED** [review]
My bad... Just noticed CI failed. Please remove unused staff

**Review by sithumonline — APPROVED** [review]
Now it's good

**Comment by Blargian** [comment]
> Thanks for sending this PR, I really appreciate that.
> 
> Can you move Login stuff to `components/Login` and `components/SignUp`?
> 
> Then we're good to go 🔥🥳

Thanks, I moved it into folder "Login". I've made the Login and Signup one component. You can display login by passing prop True and display signup by passing prop False. Is it okay?

**Comment by Blargian** [comment]
> CI is failing too, Please remove unused vars @Blargian.
> 
> @sithumonline, Seems like you haven't configured `eslint` and `husky` properly!!!!!!!!
> 
> Screenshot 2021-06-30 at 20 59 24

Removed unused variable

**Comment by chamodshehanka** [comment]
> > Thanks for sending this PR, I really appreciate that.
> > Can you move Login stuff to `components/Login` and `components/SignUp`?
> > Then we're good to go 🔥🥳
> 
> Thanks, I moved it into folder "Login". I've made the Login and Signup one component. You can display login by passing prop True and display signup by passing prop False. Is it okay?

yes, that's totally okay.

**Comment by chamodshehanka** [comment]
I gonna merge this PR, @Blargian Thank you so much for your contribution. 🔥

**Review by chamodshehanka — APPROVED** [review]

**Comment by Blargian** [comment]
> I gonna merge this PR, @Blargian Thank you so much for your contribution. 🔥

Thank you, It's a great project. Happy to help out! 💯

**Comment by chamodshehanka** [comment]
> > I gonna merge this PR, @Blargian Thank you so much for your contribution. 🔥
> 
> Thank you, It's a great project. Happy to help out! 💯

@Blargian  we would love to get more PRs from you 👀

**Comment by Blargian** [comment]
@Shehanka I'd love to help more. Which issue do you need me to work on?

**Pull request merged**
